name: Test - Spock

on:
  workflow_call:
    inputs:
      build-run-id:
        required: true
        description: Build Run ID to access uploaded artifacts
        type: string

  workflow_dispatch:
    inputs:
      build-run-id:
        required: true
        description: Build Run ID to access uploaded artifacts
        type: string

defaults:
  run:
    shell: bash

jobs:
  test-spock:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # LTS versions
        java: [ 11, 17, 21 ]
        groovy:
          - v3.0-jdk21lts
          - v4.0-jdk21lts
          - v5.0
        include:
          - java: 11
            groovy: v2.5-jdk17lts
          - java: 17
            groovy: v2.5-jdk17lts
          - java: 21
            groovy: v2.5-jdk21lts
          - java: 25
            groovy: v3.0-jdk25lts
          - java: 25
            groovy: v4.0-jdk25lts
          - java: 25
            groovy: v5.0

    steps:
      - name: Generate cache key
        id: cache-key
        run: |
          CURRENT_BRANCH="${{ github.repository != 'cdi-unit/cdi-unit' && 'fork' || github.base_ref || github.ref_name }}"
          CURRENT_MONTH=$(/bin/date -u "+%Y-%m")
          CURRENT_DAY=$(/bin/date -u "+%d")
          ROOT_CACHE_KEY="m2-cache"
          echo "m2-monthly-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}" >> $GITHUB_OUTPUT
          echo "m2-monthly-branch-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}-${CURRENT_BRANCH}" >> $GITHUB_OUTPUT
          echo "m2-cache-key=${ROOT_CACHE_KEY}-${CURRENT_MONTH}-${CURRENT_BRANCH}-${CURRENT_DAY}" >> $GITHUB_OUTPUT

      - uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Restore Maven Repository
        uses: actions/cache/restore@v5
        with:
          enableCrossOsArchive: true
          path: ~/.m2/repository
          key: ${{ steps.cache-key.outputs.m2-cache-key }}
          restore-keys: |
            ${{ steps.cache-key.outputs.m2-monthly-branch-cache-key }}-
            ${{ steps.cache-key.outputs.m2-monthly-cache-key }}-

      - name: Download .m2/repository/io/github/cdi-unit
        uses: actions/download-artifact@v6
        with:
          name: m2-io-github-cdi-unit
          path: .
          run-id: ${{ inputs.build-run-id }}

      - name: Extract .m2/repository/io/github/cdi-unit
        run: tar -xzf m2-io-github-cdi-unit.tgz -C ~

      - name: Test Spock with Groovy ${{ matrix.groovy }}
        run: ./ci-support/test-spock.sh groovy-${{ matrix.groovy }}.sh

      - name: Upload failure Archive (if maven failed)
        uses: actions/upload-artifact@v6
        if: failure()
        with:
          name: test-reports-jdk${{ matrix.java }}-groovy${{ matrix.groovy }}
          path: '**/target/surefire-reports/**'
